### PR TITLE
Add overwrite argument to gs_upload()

### PR DESCRIPTION
**Pull request by omgjens**
overwrite specifies whether a user wants to overwrite an existing sheet with an identical name when uploading a file

### CODE REVIEW

**Comment by jennybc** [comment]
Would you add a test? I need to refactor this package so it is easier to test and easier for others to test. So if this is too much of a pain, I can do it. I have not made it easy for a contributor.

**Comment by omgjens** [comment]
Thanks for your comment jennybc, I've added a test for this

**Comment by diegocgaona** [comment]
Hi, It works?
With it I can upload and replace a file, without change the url of the file?
Another doubt, how I can do it with a file in a folder?

Thanks!!

**Comment by omgjens** [comment]
Hi Diego,

1) Yes it works
2) Yes, you can upload a new or replace an existing file
3) Good question. I am not sure if it works with folders. I have only
tested it using files in the root folder. You can verify top see if it
works or change the code a little bit if it doesn't

Regards,
Jens



Op 29 jan. 2017 11:50 p.m. schreef "Diego Gaona" <notifications@github.com>:

Hi, It works?
With it I can upload and replace a file, without change the url of the file?
Another doubt, how I can do it with a file in a folder?

Thanks!!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jennybc/googlesheets/pull/285#issuecomment-275952999>,
or mute the thread

**Comment by jennybc** [comment]
Thanks @omgjens! I needed `overwrite = TRUE` this evening, in fact. So I played around with it some myself and put the finishing touches on.

**Comment by omgjens** [comment]
That's great to hear Jen, I hope many others will enjoy it too

Op 7 feb. 2017 07:47 schreef "Jennifer (Jenny) Bryan" <
notifications@github.com>:

Thanks @omgjens <https://github.com/omgjens>! I needed overwrite = TRUE
this evening, in fact. So I played around with it some myself and put the
finishing touches on.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/jennybc/googlesheets/pull/285#issuecomment-277915814>,
or mute the thread

**Pull request merged**
