### PR TITLE
Use xml2::xml_find_first() instead of deprecated xml2::xml_find_one()

### PR DESCRIPTION
**Pull request by jimhester**
The next version of xml2 will be deprecating xml_find_one() in favor of
xml_find_first(). The new function is a drop in replacement for the old, and no
longer issues a warning when more than one result would be returned.

### CODE REVIEW

**Comment by jennybc** [comment]
There's no version number associated with this change to `xml2`, right? I have to put `xml2`in `Remotes`? Do I / should I also specify a SHA?

**Comment by jimhester** [comment]
xml2 is already in `Remotes`, which is why I didn't do anything with remotes with this PR. Pinning it to a particular SHA is up to you, I would just leave it and let it float personally.

**Comment by jennybc** [comment]
Sorry I phrased that poorly. For my general education, will you confirm that this is what it means to put a package in `Remotes`? "Consider it out of date and re-install if there have been commits on github master since I last installed."

**Comment by jennybc** [comment]
Thanks for making all these changes for me BTW.

**Comment by jimhester** [comment]
It is the same behavior if you run `install_github("user/repo")` which is to install the latest version if it has been updated since the last time it was installed.

**Pull request merged**
